### ISSUE TITLE
проект полная хуйня

### ISSUE THREAD

**Issue by SDenTronS** [GigantPro/factorio#3]
ПРОЕКТ ВООБЩЕ ЛУЧШИЙ ПРОСТО В АФИГЕ КАК КРТО ПРОДОЛЖАЙТЕ РАБОТАТЬ У ВАС ВСЕ ПОЛУЧИТСЯ!!!

**Comment by prMaRKoFpr** [comment]
We're very disappointed that our project is disliked by u. We will more harder. please check updates later

**Comment by SDenTronS** [comment]
`
